package com.sparkydots.kaggle.hd.load

import org.scalatest.{FlatSpec, Matchers}


class TestCleanText extends FlatSpec with Matchers {

  val ts = Seq(

  "helloWorld",

    "The Cooper Wiring Devices 20-Amp AFCI Duplex Receptacle is the perfect outlet for any commercial or residential application. Arc fault circuit interrupters have been established as a stable technology which can be used in conjunction with various loads through the home in both AFCI breakers and AFCI receptacles. This device protects against arc faults resulting from damaged insulation and other causes that can lead to electrical fires. For increased safety, this receptacle is Tamper Resistant and meets 2014 NEC Article 406.12 which states that all 15-Amp and 20-Amp, 125-Volt/AC receptacles installed in dwelling units must be tamper resistant. Meets and exceeds 10ka Short Circuit Testing and Underwriters Laboratories UL 1699A and UL 498 Safety standards. Ground termination with back wire clamp provides secure wiring and reduces installation time. Line side terminals are backed out and staked for fast installation. When downstream receptacles are wired from load side, a 20-Amp feed-through rating offers full protection. Terminal and mounting screws have tri-combo heads for versatile installation. Cooper Wiring Devices is dedicated to providing the most up-to-date wiring device solutions; solutions that increase energy efficiency, increase productivity, promote safety at work and in the home and produce reliable performance. Cooper Wiring Devices has been a trusted name in electrical products for over 175-years.Features arc fault technology that saves lives and is an industry standard in new constructionArc fault technology has been proven through arc fault breakersHas gone through several iterations to reduce unwanted trippingBuilt with all of the latest electrical safety technology"
    ,"Discover the many benefits of Veranda Pro-Series vinyl fencing. From innovative design to durable construction to a neighbor-friendly appearance, Veranda is the perfect solution for a fence project. Made of low-maintenance vinyl, Veranda fencing is built to last for years of enjoyment.Low maintenance vinylHefty profile provides a stately appearance and excellent durabilityNever needs painting or staining4 ft. vinyl panels offer privacy with a neighbor friendly designThere is one complete panel in each box, this includes top and bottom rails and pickets, posts, post caps and hardware sold separately"
    ,"""The ""Ultra Protect"" Aluminum Basement Window Well Egress Escape Ladder is a necessary component designed to assist you and your family in a quick and safe exit from the basement level of your home through the window well in case of emergency. The Model 3ESL is designed for use in typical corrugated steel window wells measuring 42 to 54 in. in depth and includes all required assembly and installation hardware for corrugated steel wells. The 3ESL can also be mounted to all types of window wells (concrete, block, timber, etc.) using alternative mounting hardware (not included). Assembly is quick and easy using common household hand tools. Rated for 200 lbs. and meets or exceeds IBC & IFC building codes. Constructed using lightweight aluminum angle and includes anti-slip safety tape for the stepping surface of the ladder rungs. This model is also available in a 300 lb. weight rating Galvanized Steel version, model # GS-3ESL. Also choose from our complete line of ""Ultra Protect"" Basement Window Well Covers featuring our ""SAF-T Lock"" locking system with 21 stock sizes to choose from.Update your home to be IFC and IBC building code compliant by installing an ""Ultra Protect"" egress escape ladder in your basement window wellAids in climbing out the basement level of the home through the window well in case of emergencyConstructed using lightweight aluminum angle and includes anti-slip safety tape for the stepping surfaceDesigned for steel corrugated window wells measuring 42 in. to 54 in. in depthAlternative mounting hardware for all types of wells (concrete, block, timber, etc.) also availableModel is also available in a 300 lbs. weight rating galvanized steel version, model # GS-3ESLAlso choose from our complete line of ""Ultra Protect"" basement window well covers featuring our ""SAF-T Lock"" locking system with 21 stock sizes to choose fromPractice emergency exit routes so all family members become familiar with unlocking windows and climbing out window wells safelyLifetime warranty"""
  ,"The Decor Grates 4 in. x 8 in. Plastic Floor Register features the elegant look of mahogany. It easily installs in a new opening or replaces an existing register.Plastic floor register with the elegant look of mahogany wood grainLouveredEasy-to-open/close, rustproof damper boxEasily installs in an existing or new 4 in. x 8 in. openingEasy opening/closing rust-proof damper box"
  ,"Replace lost, worn, or damaged solenoids on jar-top valves used in your irrigation system with the Toro Jar-Top Valve Solenoid. The solenoid is pre-wired with an 18 in. valve-control wire and is compatible with Toro jar-top in-line and anti-siphon valves.Replaces lost, worn or damaged solenoidsHelps restore a jar-top valve's automatic operationCompatible with Toro jar-top in-line and anti-siphon valvesInstalls easily with Toro grease cap model 53687 (not included)Captive solenoid plunger helps prevent lost parts during maintenancePre-wired with an 18 in. valve-control wire"
  ,"Bring the game to your game room, garage or collection with an officially licensed beveled wood dart cabinet. Enjoy competition among friends while pre-gaming, during halftime or at the after party. It includes a high-quality, self-healing sisal fiber dartboard, 6 steel tipped darts and dry-erase scoreboard, out chart, marker and mounting supplies.Self-healing sisal fiberRemovable number ringOfficial 18 in. DiaIncludes 6 steel tip dartsDimensions (closed): D 3.5 in. x W 20.5 in. x H 24.75 in.Solid pine constructionDove tail jointsBeveled doorsMetal hingesInterior door mounted dry erase scoreboard and out chart2 magnetic markers with erasers"
  ,"Ditra is a polyethylene uncoupling underlayment with a grid structure of square cutback cavities and an anchoring fleece laminated to the underside. Ditra provides uncoupling through the open rib structure which allows for in-plane movement that effectively neutralizes the differential movement stresses between the substrate and the tile, thus eliminating the major cause of cracking and delaminating of the tiled surface. Ditra provides waterproofing and vapor management. Underlayment for tile.Designed for use with ceramic and stone tileIdeal for interior and exterior tile and stone installationsNeutralizes stress that originates in the subfloor to eliminate the main cause of tile crackingWaterproofs and allows moisture in the substrate to evaporateReplaces backboard or a second layer of plywoodPolyethylene material54 sq. ft. roll measuring 3 ft. 3 in. x 16 ft. 5 in.1/8 in. thick membrane makes transitioning to other surfaces simpleEasy installation over a thinset mortar"
  ,"Poplar S4S Boards are a great way to update your rooms and highlight the special care that has gone into your property. Featuring only the finest grade, you can achieve a rustic or natural wood look very easily. S4S boards can increase the value of your home or business estate and are an inexpensive way to add character and flair to any room.California residents: see&nbsp;Proposition 65 informationPremium clear poplar for enhanced quality and appearancePale yellow to white, with occasional streaks of gray or greenStraight, uniform grain that is easy to work with and great for utility applicationsSmooth surface requiring minimal sanding reducing labor time and costsCan be stained and/or clear-coated to achieve a beautiful finishPerfect for a variety of home improvement projects"
  ,"The cornerstone of this collection is quality, and this incandescent flush mount is no exception. Combining a classic brass finish and posh styling, you will find no better way to highlight the charm of your home. With the superb craftsmanship and affordable price this fixture is sure to tastefully indulge your extravagant side.Uses (3) incandescent bulbsBulb(s) includedEasy installation instructions and template enclosed for convenient setupIncludes installation hardwareAdds transitional styling and visual interest to your decor"
  ,"Heavily pigmented primer seals porous surfaces. Use gesso as a first layer to cover old paint, seal and prepare a surface or add tooth and increase paint adhesion. Ideal for heavily grained or darkly stained surfaces.Can be tinted using any Martha Stewart Crafts acrylic paintCan be used over old paint to seal and prepare surfaceWater based non-toxic formulaClean up while wet with soap and water"
  ,"EnviroLite low profile ceiling light fixtures are designed to enhance any decor and with a clean, fresh appearance. This modern LED ceiling light fixture easily mounts flush with the ceiling, and the low profile design keeps it out of the way of closet doors. The protective brushed nickel finish will look great for years to come, and the white lens diffuses the LED light evenly. You won't see any dark spots or shadows. This flush mount uses a LED powered lighting engine instead of lamps to produce higher quality light for a fraction of the electricity, saving you money off your utility bill. This light fixture produces 1450 lumens (about the equivalent of two 75-Watt bulbs) using only 25-Watts. The LED lighting source is made to last for 45 years at 3 hours per day; there are no bulbs to replace -ever. This ceiling fixture is ENERGY STAR listed and environmentally friendly.Streamlined to fit above doorsBrushed nickel finish; white diffuser1450 Lumens (brightness of (2) 100-Watt bulbs, 4,000K CCT (bright white), uses 25-WattsENERGY STAR listedLED life 50,000 hours120-VoltDimmable with triac dimmerHome Depot Protection Plan:"
  ,"This heavy-duty steel constructed roller is a perfect replacement for sectional overhead garage door rollers. It features a 10-ball bearing design that affords a long lasting performance. This type of roller is used by many garage door manufacturers.Heavy duty steel roller with steel inner race10 Ball bearingsShort stemEasy to install"
  ,"Pennington Southern Contractors Mix provides quick grass coverage for both sunny and light shady areas. Developed with the professional contractor in mind.Provides quick, dense grass coverageFormulated and mixed specifically for your region of the countryPenkoted technology protects the seed from deadly fungus during the early growth period when grass is more susceptible to diseaseBest for use in sunny to partly shaded areas (4-6 hours of sun per day)Germinates in 7-14 daysCovers up to 3,000 sq. ft."
  ,"lumber4x4 Lumber4 4x6treated Pennington Southern Contractors Mix provides quick grass coverage for both sunny and light shady areas. Developed with the professional contractor in mind.Provides quick, dense grass coverageFormulated and mixed specifically for your region of the countryPenkoted technology protects the seed from deadly fungus during the early growth period when grass is more susceptible to diseaseBest for use in sunny to partly shaded areas (4-6 hours of sun per day)Germinates in 7-14 daysCovers up to 3,000 sq. ft."
  )




  "CleanText" should "work" in {
    for(t <- ts)
    {
      val tt = CleanText.clean(t)
      println(t)
      println(tt)
      println()
    }

  }
}
